/* eslint-disable */
// @ts-nocheck
// This file is automatically generated by TanStack Router
// You should NOT make any changes to this file manually

import { createRootRoute, createRoute } from '@tanstack/react-router'
import { ComponentType } from 'react'

declare module '@tanstack/react-router' {
  interface fileRoutesByFullPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: ComponentType
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: ComponentType
      parentRoute: typeof rootRoute
    }
    '/pos': {
      id: '/pos'
      path: '/pos'
      fullPath: '/pos'
      preLoaderRoute: ComponentType
      parentRoute: typeof protectedRoute
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: ComponentType
      parentRoute: typeof protectedRoute
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: ComponentType
      parentRoute: typeof protectedRoute
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: ComponentType
      parentRoute: typeof protectedRoute
    }
    '/sales': {
      id: '/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: ComponentType
      parentRoute: typeof protectedRoute
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: ComponentType
      parentRoute: typeof protectedRoute
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: ComponentType
      parentRoute: typeof protectedRoute
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: ComponentType
      parentRoute: typeof protectedRoute
    }
  }
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: ComponentType
      parentRoute: typeof protectedRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: ComponentType
      parentRoute: typeof rootRoute
    }
    '/pos': {
      id: '/pos'
      path: '/pos'
      fullPath: '/pos'
      preLoaderRoute: ComponentType
      parentRoute: typeof protectedRoute
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: ComponentType
      parentRoute: typeof protectedRoute
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: ComponentType
      parentRoute: typeof protectedRoute
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: ComponentType
      parentRoute: typeof protectedRoute
    }
    '/sales': {
      id: '/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: ComponentType
      parentRoute: typeof protectedRoute
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: ComponentType
      parentRoute: typeof protectedRoute
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: ComponentType
      parentRoute: typeof protectedRoute
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: ComponentType
      parentRoute: typeof protectedRoute
    }
  }
}

// Create the root route
const rootRoute = createRootRoute()

// Create the protected route
const protectedRoute = createRoute({
  getParentRoute: () => rootRoute,
  id: 'protected',
})

// Create individual routes
const indexRoute = createRoute({
  getParentRoute: () => protectedRoute,
  path: '/',
})

const loginRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: '/login',
})

const posRoute = createRoute({
  getParentRoute: () => protectedRoute,
  path: '/pos',
})

const productsRoute = createRoute({
  getParentRoute: () => protectedRoute,
  path: '/products',
})

const customersRoute = createRoute({
  getParentRoute: () => protectedRoute,
  path: '/customers',
})

const inventoryRoute = createRoute({
  getParentRoute: () => protectedRoute,
  path: '/inventory',
})

const salesRoute = createRoute({
  getParentRoute: () => protectedRoute,
  path: '/sales',
})

const reportsRoute = createRoute({
  getParentRoute: () => protectedRoute,
  path: '/reports',
})

const settingsRoute = createRoute({
  getParentRoute: () => protectedRoute,
  path: '/settings',
})

const profileRoute = createRoute({
  getParentRoute: () => protectedRoute,
  path: '/profile',
})

// Create the route tree
export const routeTree = rootRoute.addChildren([
  loginRoute,
  protectedRoute.addChildren([
    indexRoute,
    posRoute,
    productsRoute,
    customersRoute,
    inventoryRoute,
    salesRoute,
    reportsRoute,
    settingsRoute,
    profileRoute,
  ]),
])